export const fyersData = {
  "appId": "UGY069G3IZ-100",
  "secretId": "7DNKQGSG6K",
  "redirectUrl": "https://api.ghontu.in/token",
  "fyers_acess_token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJhcGkuZnllcnMuaW4iLCJpYXQiOjE2ODkwNzEwNzgsImV4cCI6MTY4OTEyMTgzOCwibmJmIjoxNjg5MDcxMDc4LCJhdWQiOlsieDowIiwieDoxIiwieDoyIiwiZDoxIiwiZDoyIiwieDoxIiwieDowIl0sInN1YiI6ImFjY2Vzc190b2tlbiIsImF0X2hhc2giOiJnQUFBQUFCa3JTM21DQlc3RUZSOHJhSkQzX3lDd1JrMnk3VzlFVnlPbnY3UEJZUEgwOHdlV0d6eEM0VmNWS1lHOFpNQkFSd3VIRUIxMGI5VWxzZEE3NnNhUXJkZFQ5TzJEV1QwMnVmQ0d5YTRVa2pJWnJsdUZTUT0iLCJkaXNwbGF5X25hbWUiOiJTQUhBREVCIEJBUk1BTiIsIm9tcyI6IksxIiwiZnlfaWQiOiJEUzAyMjgzIiwiYXBwVHlwZSI6MTAwLCJwb2FfZmxhZyI6Ik4ifQ.WRhB25rBMlgLNwjSE28yFXj41ZQ6wdqFo8zKRKUoIr4"
};